import json

from django.conf import settings
from django.core.management import BaseCommand, CommandError

from core.ai.cache import FIXTURE_MODEL, cache_key, load_fixtures, prompt_version
from core.management.commands.seed import read_markdown
from core.models import Pin, Source
from core.services.ai_review import same_scope


class Command(BaseCommand):
    help = "Write clearly labelled synthetic AI fixtures, not real model output."

    def handle(self, *args, **options):
        if not settings.DEBUG:
            raise CommandError("Synthetic fixture generation is restricted to debug mode.")
        entries = {}

        def add(task, data, output):
            version = prompt_version(task)
            key = cache_key(task, FIXTURE_MODEL, version, data)
            entries[key] = {
                "key": key,
                "task": task,
                "model": FIXTURE_MODEL,
                "prompt_version": version,
                "input": data,
                "output": output,
            }

        pins = list(Pin.objects.filter(superseded_by__isnull=True, excluded=False))
        conflicts = [
            {"BE-PAY-CHK-2022", "BE-PAY-PROC-001"},
            {"CORRECTION-V1", "CORRECTION-V3"},
            {"CORRECTION-V1", "CORRECTION-TEAMS"},
            {"CLIENT-DEKROON", "TEAMS-BE-CONSULTANTS-20260922"},
        ]
        for pin in pins:
            add(
                "extract_claims",
                {"passage": pin.quote},
                {
                    "claims": [
                        {
                            "quote": pin.quote,
                            "subject": pin.topic.name,
                            "value": "Synthetic evidence fixture",
                        }
                    ]
                },
            )
            for other in pins:
                if pin.pk == other.pk or not same_scope(pin, other):
                    continue
                relation = (
                    "CONTRADICTS"
                    if {pin.source.external_id, other.source.external_id} in conflicts
                    else "UNRELATED"
                )
                add(
                    "compare_claims",
                    {"a": pin.quote, "b": other.quote},
                    {"relation": relation, "quote_a": pin.quote, "quote_b": other.quote},
                )
        old = Source.objects.get(external_id="TELEWORK-PC200").pins.order_by("pk").first().quote
        _, body = read_markdown(settings.BASE_DIR / "seed/sources/telework-v2.md")
        new = body.split("\n\n")[1]
        add("triage_change", {"old": old, "new": new}, {"label": "VALUE_CHANGED"})
        path = settings.BASE_DIR / "seed/ai-cache.json"
        path.write_text(
            json.dumps(
                {
                    "provenance": "Synthetic hand-authored fixtures. Not generated by Gemini.",
                    "entries": list(entries.values()),
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        load_fixtures()
        self.stdout.write(f"Wrote {len(entries)} synthetic fixtures.")
